### ISSUE TITLE
Document all of the options to the initializer

### ISSUE THREAD

**Issue by wraithan** [flightstats/node-insights#15]
There are a number of options, I've had to dig into the source to see them.

**Comment by mattpage** [comment]
Ok, looking at the configuration options,  some of these are head scratchers.
Here's the results of my initial investigation:

**enabled** - is used to disable the sending of insights data. There appears to be no way to re-enable it if you disable it. Should we remove this option or provide setter/getters?

**logger** - see #16 

**insertKey, queryKey, and accountId** are all documented with this passive nugget: 

```
insertKey, queryKey, and accountId can all be found in one's NewRelic dashboard.
```

**timerInterval** - is pretty straightforward. Perhaps, "The timer interval (in milliseconds) that is used for sending data. Defaults to 10000ms"

**maxPending** - Alluded to "Data is held in the queue until either the number of items exceeds maxPending or the send timer goes off." Probably should say something like: "The maximum number of items held in the queue before being sent.  Defaults to 1000"

**defaultEventType** - This is mentioned in the "event types" section.
```
When you add data, you can specify the eventType that is sent to New Relic.
If you don't specify the eventType, the defaultEventType (from the initial config is used).
The defaultEventType **defaults** to the string 'data'. Awesome!
```

**baseURL** - appears to be unused.
**url** - appears to be unused. It is built dynamically in send each time.

Additionally neither of these are documented:

Insights.collectorBaseURL = "https://insights-collector.newrelic.com";
Insights.queryBaseURL = "https://insights-api.newrelic.com";

**Comment by mattpage** [comment]
I added a getter/setter for the enabled param. The rest of these have been documented in jsdoc. @wraithan I defer to you on whether jsdoc is sufficient or should we replicate the docs into the readme or what? Thanks

**Comment by mattpage** [comment]
Nevermind, I went ahead and just added the docs to the README.md too.
