### ISSUE TITLE
not reducing

### ISSUE THREAD

**Issue by matiasdecarli** [flightstats/node-insights#18]
Hi, im hitting a `non reducing` all the time

```javascript
      //ignore functions, nulls, undefineds
      logger.warn('not reducing', prefix, key, value);
```

Can anyone give me some explanation on this and how can I fix it? I can't understand why it happens

Thanks in advance

**Comment by mattpage** [comment]
Hey @matiasdecarli 

What are you passing into the add method? 
What is the complete log output (prefix, key, value)?

Remember that insights only accepts simple values. 
The point of the reduce method is to reduce objects and arrays to simple values.

**Comment by matiasdecarli** [comment]
The log output is 
```
not reducing  param1 undefined
not reducing  param2 undefined
not reducing  param3 undefined
not reducing  param4 undefined
```

**Comment by matiasdecarli** [comment]
Also @mattpage is there any way to avoid logging to the console when an operation is successful?

**Comment by mattpage** [comment]
@matiasdecarli 

Well, you can pass a custom logger and eat the .log calls if you want.
#16 is all about documenting the logger and what-not. Sort of on my radar.
