### ISSUE TITLE
Dependency vulnerability 

### ISSUE THREAD

**Issue by se7en7x** [flightstats/node-insights#24]
=== npm audit security report ===

                                 Manual Review
             Some vulnerabilities require your attention to resolve

          Visit https://go.npm.me/audit-guide for additional guidance

  Low             Prototype Pollution

  Package         lodash

  Patched in      >=4.17.5

  Dependency of   node-insights

  Path            node-insights > lodash

  More info       https://nodesecurity.io/advisories/577

found 1 low severity vulnerability in 6853 scanned packages
  1 vulnerability requires manual review. See the full report for details.

**Comment by cmwood** [comment]
Dependencies addressed.
